export const CHANGE_PRODUCT_DETAIL = 'CHANGE_PRODUCT_DETAIL'

export const ADD_TO_CARTS = 'ADD_TO_CARTS'

export const CHANGE_CART_QUANTITY = 'CHANGE_CART_QUANTITY'

export const DELTETE_CART_ITEM = 'DELTETE_CART_ITEM'
